language: node_js
dist: trusty
node_js:
- '6.10'
- '7.10'

services:
  - redis-server
  - docker

branches:
  only:
  - master
  - /^[0-9]+.[0-9]+.[0-9]+(-.*)?$/
  - /^greenkeeper/.*$/

cache:
  directories:
  - node_modules

env:
  - DB=mysql PARSE_SERVER_TEST_DB=mysql
  - DB=mariadb PARSE_SERVER_TEST_DB=mysql
  - PARSE_SERVER_TEST_CACHE=redis

global:
- COVERAGE_OPTION='./node_modules/.bin/nyc'

before_install:
-  chmod +x ./resources/*
- ./resources/travis_mysql_5.7.sh
- ./resources/mysql-reset-root-password.sh
- mysql -e 'CREATE DATABASE parse_server_mysql_adapter_test_database;'

before_script:
- node -e 'require("./lib/index.js")'

after_script:
- bash <(curl -s https://codecov.io/bash)
